name: Backport labeled merged pull requests
on:
  pull_request:
    types: [closed]
  issue_comment:
    types: [created]
jobs:
  build:
    name: Create backport PRs
    runs-on: ubuntu-latest
    # Only run when pull request is merged
    # or when a comment containing `/backport` is created
    if: >
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.merged
      ) || (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.comment.user.id != 97796249 &&
        contains(github.event.comment.body, '/backport')
      )
    steps:
      - uses: actions/checkout@v5
        with:
          # Token for git actions, e.g. git push, needed to be able to e.g. update workflow files
          token: ${{ secrets.BACKPORT_ACTION_PAT }}
      - name: Create backport PRs
        uses: korthout/backport-action@v3
        with:
          github_token: ${{ secrets.BACKPORT_ACTION_PAT }}

          # Optional
          # Template used as description in the pull requests created by this action.
          # Placeholders can be used to define variable values.
          # These are indicated by a dollar sign and curly braces (`${placeholder}`).
          # Please refer to this action's README for all available placeholders.
          pull_description: |-
            # Description
            Backport of #${pull_number} to `${target_branch}`.

            relates to ${issue_refs}
